name: Adhoc tests
on:
  workflow_dispatch:
    inputs:
      path:
        description:
            "Path of the notebook/script to test, relative to the repo root.
            For scripts, this should be the path of the `scripts` folder"
        required: true
        type: string
      python_version:
        description: "Python version"
        required: true
        default: "3.10"
        type: choice
        options:
            - "3.9"
            - "3.10"
            - "3.11"
            - "3.12"
            - "3.13"
      os:
        description: "Windows/Ubuntu/MacOS"
        required: true
        default: "ubuntu-latest"
        type: choice
        options:
            - ubuntu-latest
            - macos-13
            - windows-latest
env:
  PYTHONIOENCODING: utf-8
  PYTHONLEGACYWINDOWSSTDIO: utf-8
  NEPTUNE_PROJECT: ${{ vars.NEPTUNE_PROJECT }}
jobs:
  run-tests:
      runs-on: ${{ inputs.os }}
      steps:
          - uses: actions/checkout@main
          - uses: actions/setup-python@main
            with:
              python-version: ${{ inputs.python_version }}
              cache: "pip"
          - name: Upgrade pip
            run: python -m pip install --upgrade pip
          - name: Install setuptools for python>=3.12
            if: inputs.python_version >= 3.12
            run: pip install -U setuptools
          - name: Install libomp on MacOS
            if: inputs.os == 'macos-13'
            run: brew install libomp
          - name: Test scripts
            if: endsWith(inputs.path, 'scripts')
            uses: nick-fields/retry@v3
            env:
                NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
            with:
                timeout_minutes: 60
                max_attempts: 2
                command: |
                    cd ${{ inputs.path }}
                    bash run_examples.sh
          - name: Test notebooks
            if: endsWith(inputs.path, '.ipynb')
            uses: nick-fields/retry@v3
            env:
                NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
            with:
                timeout_minutes: 60
                max_attempts: 2
                command: |
                    ipython ${{ inputs.path }}
