name: Scheduled scripts tests (ubuntu)
on:
  schedule:
    - cron: "0 0 * * 3" # Run every Wednesday at 12:00 AM UTC
  workflow_dispatch:
jobs:
  test-scripts-ubuntu:
    uses: ./.github/workflows/test-scripts.yml
    with:
      os: ubuntu-latest
    secrets:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
